#include "console/console.h"

//TODO: INSTEAD OUTPUT TO A STREAMLINE AND OUTPUT SAVED CHANGES TO A DIFFERENT FILE OR OVERWRITE (REBASE ALL OTHER ELEMENTS ACCORDING TO THE SORTED ONE).
//TODO: WHEN REMOVING CHAR TYPE ELEMENTS MUST FREE MEMORY OF OBJECT.

int main() {
  console();
  return 0;
}
